import {
  TILE_ROCK,
  TILE_EAT,
  TILE_EMPTY,
  TILE_WATER,
  TILE_HILL
} from "./tiles";

export const MAP_STANDART = [
  [
    TILE_ROCK,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_ROCK,
    TILE_WATER,
    TILE_EAT
  ],
  [
    TILE_EAT,
    TILE_EMPTY,
    TILE_WATER,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY
  ],
  [
    TILE_EMPTY,
    TILE_HILL,
    TILE_EMPTY,
    TILE_EAT,
    TILE_ROCK,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_ROCK
  ],
  [
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_HILL,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_ROCK,
    TILE_EMPTY,
    TILE_HILL,
    TILE_EMPTY
  ],
  [
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_WATER,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY
  ],
  [
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_ROCK,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY
  ],
  [
    TILE_WATER,
    TILE_EMPTY,
    TILE_ROCK,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_ROCK,
    TILE_ROCK,
    TILE_WATER,
    TILE_EMPTY,
    TILE_EMPTY
  ],
  [
    TILE_EMPTY,
    TILE_ROCK,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EAT,
    TILE_EMPTY,
    TILE_HILL,
    TILE_EMPTY
  ],
  [
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_ROCK,
    TILE_EMPTY
  ],
  [
    TILE_WATER,
    TILE_HILL,
    TILE_EMPTY,
    TILE_WATER,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_HILL,
    TILE_EAT,
    TILE_EMPTY,
    TILE_ROCK
  ]
];

export const MAP_TREES = [
  [
    TILE_WATER,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_ROCK,
    TILE_WATER,
    TILE_EAT
  ],
  [
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_WATER,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT
  ],
  [
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_ROCK,
    TILE_EMPTY,
    TILE_HILL,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY
  ],
  [
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_HILL,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_HILL,
    TILE_EMPTY
  ],
  [
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_WATER,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY
  ],
  [
    TILE_EAT,
    TILE_EMPTY,
    TILE_WATER,
    TILE_ROCK,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY
  ],
  [
    TILE_EMPTY,
    TILE_EAT,
    TILE_ROCK,
    TILE_EMPTY,
    TILE_HILL,
    TILE_ROCK,
    TILE_EMPTY,
    TILE_WATER,
    TILE_EMPTY,
    TILE_EAT
  ],
  [
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EAT,
    TILE_HILL,
    TILE_EMPTY
  ],
  [
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_HILL,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY,
    TILE_EAT,
    TILE_ROCK,
    TILE_EMPTY
  ],
  [
    TILE_HILL,
    TILE_ROCK,
    TILE_EAT,
    TILE_ROCK,
    TILE_EMPTY,
    TILE_WATER,
    TILE_HILL,
    TILE_EAT,
    TILE_EMPTY,
    TILE_EMPTY
  ]
];

export const MAP_ANIMALS = [
  [[], [], [], [], [], [], [], [], [], []],
  [[], [], [], [], [], [], [], [], [], []],
  [[], [], [], [], [], [], [], [], [], []],
  [[], [], [], [], [], [], [], [], [], []],
  [[], [], [], [], [], [], [], [], [], []],
  [[], [], [], [], [], [], [], [], [], []],
  [[], [], [], [], [], [], [], [], [], []],
  [[], [], [], [], [], [], [], [], [], []],
  [[], [], [], [], [], [], [], [], [], []],
  [[], [], [], [], [], [], [], [], [], []]
];
